# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ghao/blaze/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
#PRODUCT_COPY_FILES := \
# vendor/ghao/blaze/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
# vendor/ghao/blaze/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
# vendor/ghao/blaze/proprietary/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
# vendor/ghao/blaze/proprietary/lib/libseccameraadaptor.so:obj/lib/libseccameraadaptor.so

PRODUCT_COPY_FILES += \
 vendor/ghao/blaze/proprietary/etc/powervr.ini:system/etc/powervr.ini \
 vendor/ghao/blaze/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
 vendor/ghao/blaze/proprietary/lib/hw/audio.primary.blaze.so:system/lib/hw/audio.primary.blaze.so \
 vendor/ghao/blaze/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
 vendor/ghao/blaze/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
 vendor/ghao/blaze/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
 vendor/ghao/blaze/proprietary/lib/hw/camera.omap4.so:system/lib/hw/camera.omap4.so \
 vendor/ghao/blaze/proprietary/lib/hw/gps.omap4blazeboard.so:system/lib/hw/gps.omap4blazeboard.so \
 vendor/ghao/blaze/proprietary/lib/hw/lights.blaze.so:system/lib/hw/lights.blaze.so \
 vendor/ghao/blaze/proprietary/lib/hw/sensors.blaze.so:system/lib/hw/sensors.blaze.so \
 vendor/ghao/blaze/proprietary/lib/modules/pvrsrvkm_sgx540_120.ko:system/lib/modules/pvrsrvkm_sgx540_120.ko \
 vendor/ghao/blaze/proprietary/lib/modules/pvrsrvkm_sgx544_112.ko:system/lib/modules/pvrsrvkm_sgx544_112.ko \
 vendor/ghao/blaze/proprietary/lib/libbluedroid.so:system/lib/libbluedroid.so \
 vendor/ghao/blaze/proprietary/lib/libdomx.so:system/lib/libdomx.so \
 vendor/ghao/blaze/proprietary/lib/libedid.so:system/lib/libedid.so \
 vendor/ghao/blaze/proprietary/lib/libfmradio.so:system/lib/libfmradio.so \
 vendor/ghao/blaze/proprietary/lib/libion.so:system/lib/libion.so \
 vendor/ghao/blaze/proprietary/lib/libmm_osal.so:system/lib/libmm_osal.so \
 vendor/ghao/blaze/proprietary/lib/libOMX.ITTIAM.WMA.decode.so:system/lib/libOMX.ITTIAM.WMA.decode.so \
 vendor/ghao/blaze/proprietary/lib/libOMX.ITTIAM.WMALSL.decode.so:system/lib/libOMX.ITTIAM.WMALSL.decode.so \
 vendor/ghao/blaze/proprietary/lib/libOMX.ITTIAM.WMAPRO.decode.so:system/lib/libOMX.ITTIAM.WMAPRO.decode.so \
 vendor/ghao/blaze/proprietary/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so:system/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so \
 vendor/ghao/blaze/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so:system/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so \
 vendor/ghao/blaze/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.secure.so:system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.secure.so \
 vendor/ghao/blaze/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so:system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so \
 vendor/ghao/blaze/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so:system/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so \
 vendor/ghao/blaze/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so:system/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so \
 vendor/ghao/blaze/proprietary/lib/libtiutils.so:system/lib/libtiutils.so \
 vendor/ghao/blaze/proprietary/lib/libxgold-ril.so:system/lib/libxgold-ril.so \
 vendor/ghao/blaze/proprietary/vendor/bin/pvrsrvinit_SGX540_120:system/vendor/bin/pvrsrvinit_SGX540_120 \
 vendor/ghao/blaze/proprietary/vendor/bin/pvrsrvinit_SGX544_112:system/vendor/bin/pvrsrvinit_SGX544_112 \
 vendor/ghao/blaze/proprietary/vendor/bin/pvrsrvinit:system/vendor/bin/pvrsrvinit \
 vendor/ghao/blaze/proprietary/vendor/firmware/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
 vendor/ghao/blaze/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
 vendor/ghao/blaze/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX544_112.so:system/vendor/lib/egl/libEGL_POWERVR_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_112.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX544_112.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/hw/gralloc.omap4430.so:system/vendor/lib/hw/gralloc.omap4430.so \
 vendor/ghao/blaze/proprietary/vendor/lib/hw/gralloc.omap4460.so:system/vendor/lib/hw/gralloc.omap4460.so \
 vendor/ghao/blaze/proprietary/vendor/lib/hw/gralloc.omap4470.so:system/vendor/lib/hw/gralloc.omap4470.so \
 vendor/ghao/blaze/proprietary/vendor/lib/hw/hwcomposer.omap4.so:system/vendor/lib/hw/hwcomposer.omap4.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libbltsville_ticpu.2.0.0.10.so:system/vendor/lib/libbltsville_ticpu.2.0.0.10.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libbltsville_ticpu_license.txt:system/vendor/lib/libbltsville_ticpu_license.txt \
 vendor/ghao/blaze/proprietary/vendor/lib/libglslcompiler_SGX540_120.so:system/vendor/lib/libglslcompiler_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libglslcompiler_SGX544_112.so:system/vendor/lib/libglslcompiler_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libIMGegl_SGX540_120.so:system/vendor/lib/libIMGegl_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libIMGegl_SGX544_112.so:system/vendor/lib/libIMGegl_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libpvr2d_SGX540_120.so:system/vendor/lib/libpvr2d_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libpvr2d_SGX544_112.so:system/vendor/lib/libpvr2d_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so:system/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libpvrANDROID_WSEGL_SGX544_112.so:system/vendor/lib/libpvrANDROID_WSEGL_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libPVRScopeServices_SGX540_120.so:system/vendor/lib/libPVRScopeServices_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libPVRScopeServices_SGX544_112.so:system/vendor/lib/libPVRScopeServices_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libsrv_init_SGX540_120.so:system/vendor/lib/libsrv_init_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libsrv_init_SGX544_112.so:system/vendor/lib/libsrv_init_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libsrv_um_SGX540_120.so:system/vendor/lib/libsrv_um_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libsrv_um_SGX544_112.so:system/vendor/lib/libsrv_um_SGX544_112.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libusc_SGX540_120.so:system/vendor/lib/libusc_SGX540_120.so \
 vendor/ghao/blaze/proprietary/vendor/lib/libusc_SGX544_112.so:system/vendor/lib/libusc_SGX544_112.so \
 vendor/ghao/blaze/proprietary/xbin/hciconfig:system/xbin/hciconfig \
 vendor/ghao/blaze/proprietary/xbin/hcitool:system/xbin/hcitool
